### ISSUE TITLE
implement auto.arima 

### ISSUE THREAD

**Issue by waynelapierre** [LAMPSPUC/StateSpaceModels.jl#248] opened 2021-03-12 15:25 UTC
The auto.arima function in the R package forecast can identify the best ARIMA model. https://www.rdocumentation.org/packages/forecast/versions/8.13/topics/auto.arima

**Comment by guilhermebodin** [comment] 2021-03-12 15:26
This is a current open issue #234

**Comment by guilhermebodin** [comment] 2021-03-16 13:45
Closing this because it is a duplicate of #234

**Closed by guilhermebodin** 2021-03-16 13:45 UTC
